# Generated by Django 4.1.6 on 2024-01-05 22:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_sales_sale_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affmkt',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='humpsy',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
