# Generated by Django 4.1.6 on 2024-01-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_affmkt_content_alter_humpsy_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sale',
            new_name='sales',
        ),
        migrations.DeleteModel(
            name='affmkt',
        ),
        migrations.DeleteModel(
            name='humpsy',
        ),
    ]
