# Generated by Django 4.1.6 on 2024-01-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_sell_delete_marketing_delete_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
