# Generated by Django 4.1.6 on 2024-01-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sell',
            new_name='sale',
        ),
    ]
