# Generated by Django 4.1.6 on 2024-01-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_sell_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sale',
            new_name='sales',
        ),
    ]
