# Generated by Django 4.1.6 on 2024-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_blog_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='writer',
        ),
        migrations.AddField(
            model_name='sales',
            name='writer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
