# Generated by Django 4.1.6 on 2024-01-08 17:21

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_blog_writer_sales_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='bl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
