# Generated by Django 4.1.6 on 2024-01-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bl',
        ),
    ]
