# Generated by Django 4.1.6 on 2024-01-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_bl'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
