# Generated by Django 4.1.6 on 2024-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_blog_title_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_3',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
