# Generated by Django 4.1.6 on 2024-01-10 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_blog_title_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at_1',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at_2',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
