# Generated by Django 4.1.6 on 2024-01-10 12:38

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='aff_mkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('writer', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='aff_mkt_pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('writer', models.CharField(blank=True, max_length=300)),
                ('aff_mkt_pg_1', models.CharField(blank=True, max_length=300)),
                ('created_at_1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('aff_mkt_2_pg_2', models.CharField(blank=True, max_length=300)),
                ('created_at_2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='human_psy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('writer', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='sales_pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('writer', models.CharField(blank=True, max_length=300)),
                ('sales_page_1', models.CharField(blank=True, max_length=300)),
                ('created_at_1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sales_page_2', models.CharField(blank=True, max_length=300)),
                ('created_at_2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
