# Generated by Django 4.1.6 on 2024-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_aff_mkt_aff_mkt_pg_human_psy_sales_pg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_pg',
            name='sales_page_1',
        ),
        migrations.RemoveField(
            model_name='sales_pg',
            name='sales_page_2',
        ),
        migrations.AddField(
            model_name='sales_pg',
            name='spt_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sales_pg',
            name='spt_2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
