# Generated by Django 4.1.6 on 2024-01-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_sales_pg_spt_1_remove_sales_pg_spt_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aff_mkt_pg',
            name='aff_mkt_2_pg_2',
        ),
        migrations.RemoveField(
            model_name='aff_mkt_pg',
            name='aff_mkt_pg_1',
        ),
        migrations.RemoveField(
            model_name='aff_mkt_pg',
            name='content',
        ),
        migrations.AddField(
            model_name='aff_mkt_pg',
            name='title_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aff_mkt_pg',
            name='title_3',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
