# Generated by Django 4.1.6 on 2024-01-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_human_ps_remove_human_psy_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',)},
        ),
    ]
