# Generated by Django 4.1.6 on 2024-01-12 13:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_aff_mkt_body_sales_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aff_mkt',
            name='content',
        ),
        migrations.RemoveField(
            model_name='human_ps',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='body',
        ),
        migrations.AlterField(
            model_name='sales',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
