# Generated by Django 4.1.6 on 2024-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_aff_mkt_content_remove_human_ps_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AddField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
