# Generated by Django 4.1.6 on 2024-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_blog_options_blog_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
