# Generated by Django 4.1.6 on 2024-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_sales_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
