# Generated by Django 4.1.6 on 2024-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_blog_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='header_image_1',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='header_image_2',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
