# Generated by Django 4.1.6 on 2024-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_blog_header_image_1_blog_header_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aff_mkt_pg',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='aff_mkt_pg',
            name='header_image_1',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='aff_mkt_pg',
            name='header_image_2',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='human_psy',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='human_psy',
            name='header_image_1',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='human_psy',
            name='header_image_2',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='sales_pg',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='sales_pg',
            name='header_image_1',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='sales_pg',
            name='header_image_2',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
