# Generated by Django 4.1.6 on 2024-01-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_aff_mkt_pg_header_image_aff_mkt_pg_header_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_pg',
            old_name='head_image',
            new_name='header_image',
        ),
    ]
