# Generated by Django 4.1.6 on 2024-01-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_aff_mkt_pg_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aff_mkt_pg',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='human_psy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sales_pg',
            options={'ordering': ['-created_at']},
        ),
    ]
